CREATE DATABASE University
USE [University]

CREATE TABLE Majors (
MajorID INT PRIMARY KEY IDENTITY,
[Name] VARCHAR(50)
)


CREATE TABLE Students (
StudentID INT PRIMARY KEY IDENTITY,
StudentNumber VARCHAR(10) NOT NULL,
StudentName NVARCHAR(50) NOT NULL,
MajorID INT NOT NULL FOREIGN KEY REFERENCES Majors(MajorId)
)

CREATE TABLE Payments (
PaymentId INT PRIMARY KEY IDENTITY,
PaymentDate DATE NOT NULL,
PaymontAmount DECIMAL(15, 2) NOT NULL,
StudentID INT NOT NULL FOREIGN KEY REFERENCES Students(StudentID)
)

CREATE TABLE Subjects (
SubjectID INT PRIMARY KEY IDENTITY,
SubjectName NVARCHAR(50) NOT NULL
)

CREATE TABLE Agenda (
StudentID INT NOT NULL FOREIGN KEY REFERENCES Students(StudentID), 
SubjectID INT NOT NULL FOREIGN KEY REFERENCES Subjects(SubjectID), 
PRIMARY KEY (StudentID, SubjectID)
)

