USE Hotel

TRUNCATE TABLE Occupancies	
TRUNCATE TABLE Payments
TRUNCATE TABLE Customers
TRUNCATE TABLE Employees
TRUNCATE TABLE RoomStatus
TRUNCATE TABLE RoomTypes
TRUNCATE TABLE BedTypes
TRUNCATE TABLE Rooms